<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="insert.js"></script>
  <title>Starwars - Spaceships</title>
</head>

<body>
  <div class="container">
    <div class="row">

      <div class="col-md-12">

        <div class="panel panel-default">
          <div class="panel-heading">
          </div>
          <div class="panel-body text-center">
            <h2>Starwars - Spaceships</h2>
          </div>
          <div class="panel-footer text-center">
            <div class="row">
              <button type="button" class="btn btn-default" onclick="location.href='../../index.phtml'">
                Lista
              </button>
              <button type="button" class="btn btn-default" onclick="location.href='insert.phtml'">
                Adicionar
              </button>
            </div>
          </div>
        </div>

        <form id="myForm" name="myForm">
          <div class="panel panel-default">
            <div class="panel-heading">
              <label class="panel-title">Adicionar Spaceship</label>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-4">
                  <label>Nome:</label>
                  <input class="form-control" type="text" id="name" name="name">
                </div>
                <div class="col-md-4">
                  <label>Modelo:</label>
                  <input class="form-control" type="text" id="model" name="model">
                </div>
              </div>
            </div>
            <div class="panel-footer text-right">
              <button type="button" class="btn btn-default" onclick="SubForm()">
                Salvar
              </button>
            </div>
          </div>
        </form>

      </div>

    </div>
  </div>
  </div>
</body>

</html>